# Site settings
title: "Niels Christoffersen GitHub Page"
description: "Personal website powered by Jekyll and GitHub Pages."
name: "Niels Christoffersen"
email: your-email@example.com

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Author information
author:
  name: "Niels Christoffersen"
  bio: "Your bio here"
  location: "Your location"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nielsjsc"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/baneofian"

# Site settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Build settings
include:
  - _pages